# Generated by Django 3.2.7 on 2021-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('max_price', models.PositiveIntegerField(verbose_name='Максимальная цена')),
                ('square', models.PositiveIntegerField(verbose_name='Площадь')),
                ('location', models.CharField(max_length=100, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Недвижимость',
            },
        ),
        migrations.CreateModel(
            name='Other_Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('max_price', models.PositiveIntegerField(verbose_name='Максимальная цена')),
            ],
            options={
                'verbose_name': 'Другое',
            },
        ),
        migrations.CreateModel(
            name='Transport_Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('max_price', models.PositiveIntegerField(verbose_name='Максимальная цена')),
                ('brand', models.CharField(max_length=40, verbose_name='Марка')),
                ('model', models.CharField(max_length=60, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Транспорт',
            },
        ),
    ]
