# Generated by Django 3.2.7 on 2021-09-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House_Ad',
            new_name='Real_Estate_Ad',
        ),
        migrations.AlterModelOptions(
            name='other_ad',
            options={'verbose_name': 'Другое', 'verbose_name_plural': 'Другое'},
        ),
        migrations.AlterModelOptions(
            name='real_estate_ad',
            options={'verbose_name': 'Недвижимость', 'verbose_name_plural': 'Недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='transport_ad',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
    ]
